### ISSUE TITLE
Other accessories?

### ISSUE THREAD

**Issue by upintheairsheep** [Hinara/gamecube-adapter#3]
Hello, it would be nice to add support for a few accessories other than the original controllers. You don't have to, but it would be useful to some.

- [ ] DK Bongos are used with this adapter as recent as the Nintendo Switch, it is a controller that includes 2 bongos and a sound sensor.
- [ ] The GameBoy Link Cable allows the Game Boy Advance to become a peripheral. The GBA's buttons could be used to control modern games based on code from the [Game Boy Interface](https://www.gc-forever.com/wiki/index.php?title=Game_Boy_Interface), specifically the enhanced mGBA port from the GitHub, and a driver for the LED could possibly (certain games allowed the use of the GBA screen) be developed similar to the [abandoned VMU display driver](https://linuxdc.sourceforge.net/berger/mlcd/) on LinuxDC. A driver for the game ROM, game save, and BIOS could also be developed based on the [link cable dumper](https://github.com/FIX94/gba-link-cable-dumper) and (rom sender)[https://github.com/FIX94/gba-link-cable-rom-sender] to dump game saves and write rewritable cartridges, and legally dump the ROMs of games, albeit with a VERY slow speed (40 minutes per dumped game). This would probably be complicated to implement, but it would pay off having Linux support the GBA as a slave device natively. GBA slot games with sensors exist if you want to develop this even further.
- [ ] The ASCII keyboard controller is a strange accessory to say the least. It is a GC controller with a keyboard. Raphnet adapters do support this controller natively, and videos about this controller have gotten views on YT, so it might be worthwhile.

**Comment by Hinara** [comment]
Hi,
I'm sorry but this does not seems feasible because of hardware constraints in the Nintendo GameCube Adapter.

> ### What controllers does the GameCube Controller Adapter support?
> The controller supports Nintendo GameCube controllers, WaveBird wireless controllers, and licensed GameCube controllers. Non-standard controllers, such as racing wheels or DK Bongo controllers are not supported - though some buttons may give a response when they are connected.

From https://en-americas-support.nintendo.com/app/answers/detail/a_id/13277/~/gamecube-controller-adapter-%26-gamecube-super-smash-bros.-edition-controller-faq

Some other unofficial adapters might be able to handle them but it seems that it is not the case for the official one :disappointed:
